### PR TITLE
Remove useless IsConnected if statement in pm command

### PR DESCRIPTION
**Pull request by duboiss**
This logic is already handled by SampSharp.

### CODE REVIEW

**Review by V1ck3s — COMMENTED** [review]
Ok but what's the error returned to the player? It is not in French, it should perhaps be left to indicate to the player the error.

**Comment by duboiss** [comment]
It's handled before the command logic. I don't think we can override this behavior.
The player just see "Usage: ...".

Same behavior for /a donner, /a give, /a delete, /mp... commands, with wrong id, who they haven't this statement.

**Comment by V1ck3s** [comment]
I think that the message sent by SAMPSharp is not precise enough, the player will not know what the problem is. Better to send a second message to clarify it or try to not send the message from SAMPSharp.
We have to look if it's possible.

**Comment by duboiss** [comment]
As I said before, it's **before** the command logic so we can't add a message for a particular command.
So the PR is always valid, it's a harmonization beetwing all commands who have a Player target argument.

**Comment by Papawy** [comment]
Actually we could extend the SampSharp command systems to make it react as we want. I will take a look at this later.

**Review by Papawy — APPROVED** [review]

**Review by Papawy — COMMENTED** [review]
We will wait for a rework of command system.

**Pull request closed without merging**
